# Generated by Django 5.2.6 on 2025-09-20 01:06

import django_document_manager.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('created_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by app')),
                ('updated_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by app')),
                ('deleted_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by app')),
                ('owner_uuid', models.UUIDField(help_text='UUID of the document owner instance')),
                ('title', models.CharField(help_text='Document title or description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of document contents', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Date the document expires (if applicable)', null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('requires_update', 'Requires Update')], default='pending', help_text='Current validation status', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, help_text='When the document was validated', null=True)),
                ('validation_notes', models.TextField(blank=True, help_text='Notes from validation process', null=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('ai_extracted_data', models.JSONField(default=dict, help_text='Data extracted from document by AI processing')),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score for extracted data (0-100)', max_digits=5, null=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Whether this document contains confidential information')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal Team'), ('restricted', 'Restricted Access'), ('confidential', 'Confidential')], default='internal', help_text='Who can access this document', max_length=20)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'dm_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('created_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by app')),
                ('updated_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by app')),
                ('deleted_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by app')),
                ('name', models.CharField(help_text='Display name of the catalog item', max_length=100)),
                ('code', models.CharField(help_text='Unique code identifier', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description for the catalog item', null=True)),
                ('description_hint', models.CharField(blank=True, help_text='Short description for UI display', max_length=255, null=True)),
                ('is_selectable', models.BooleanField(default=True, help_text='Indicates if the item can be selected in UIs')),
                ('file_extensions', models.JSONField(default=list, help_text='Allowed file extensions for this document type')),
                ('max_file_size_mb', models.IntegerField(default=10, help_text='Maximum file size in MB')),
                ('requires_validation', models.BooleanField(default=False, help_text='Whether this document type requires manual validation')),
                ('is_financial', models.BooleanField(default=False, help_text='Whether this is a financial document requiring special handling')),
            ],
            options={
                'verbose_name': 'document type',
                'verbose_name_plural': 'document types',
                'db_table': 'dm_document_type',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('created_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by app')),
                ('updated_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by app')),
                ('deleted_by_app', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by app')),
                ('file', models.FileField(help_text='The actual document file', upload_to=django_document_manager.models.models.document_upload_to)),
                ('file_size_bytes', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 hash of file contents for integrity verification', max_length=64)),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_original_name', models.CharField(blank=True, help_text='Original name of the uploaded file', max_length=255, null=True)),
                ('version', models.PositiveIntegerField(help_text='Version number of the document')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current version')),
                ('document_date', models.DateField(blank=True, help_text='Date the document was created or is effective', null=True)),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'db_table': 'dm_document_version',
                'ordering': ['document', '-version'],
            },
        ),
    ]
