# Generated by Django 5.2.6 on 2025-10-23 15:48
# Adds user foreign key relationships for audit trail

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_document_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add user foreign keys to DocumentType
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Add user foreign keys to Document
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='validated_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who validated this document',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='validated_documents',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Add user foreign keys to DocumentVersion
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='updated_%(class)s',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
