# Generated by Django 5.2.6 on 2025-11-21 14:47

import django_document_manager.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_document_manager', '0002_add_user_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('group_uuid', models.UUIDField(default=django_document_manager.models.models._generate_uuid7, editable=False, help_text='Unique identifier for the document group', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the document group', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the document group', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata for the document group', null=True)),
            ],
            options={
                'verbose_name': 'document group',
                'verbose_name_plural': 'document groups',
                'db_table': 'dm_document_group',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this document belongs to', related_name='documents', to='django_document_manager.documentgroup'),
        ),
    ]
