# Generated by Django 5.2.6 on 2025-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_document_manager', '0003_documentgroup_document_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
