# Generated by Django 5.2.6 on 2025-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_document_manager', '0004_alter_documenttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='max_count_per_owner',
            field=models.IntegerField(default=0, help_text='Maximum number of documents of this type per owner. Use 0 for unlimited.'),
        ),
    ]
