# Generated by Django 5.2.6 on 2026-01-09 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_document_manager', '0005_documenttype_max_count_per_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.CharField(blank=True, help_text='Optional tag for categorizing the document', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tag'], name='idx_document_tag'),
        ),
    ]
